version: '3.8'

services:
  # Django Backend
  backend:
    build: ./aberturas
    ports:
      - "8002:8000"
    volumes:
      - ./aberturas:/app
    environment:
      - DJANGO_SETTINGS_MODULE=aberturas.settings.dev
    env_file:
      - ./aberturas/.env
    depends_on:
      - db
      - redis
    command: >
      bash -c "
      echo 'Esperando a que la base de datos esté disponible...' &&
      while ! python manage.py check --database default; do
        echo 'Base de datos no disponible, esperando...' &&
        sleep 2
      done &&
      echo 'Base de datos disponible!' &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

  # React Frontend
  frontend:
    build: .
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

  # MySQL Database
  db:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      - MYSQL_DATABASE=aberturas
      - MYSQL_USER=aberturas
      - MYSQL_PASSWORD=aberturas
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: