version: '3.8'

services:
  login-app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true