version: '3.8'

services:
  # Django Backend
  backend:
    build: ./aberturas
    ports:
      - "8002:8000"
    volumes:
      - ./aberturas:/app
    environment:
      - DJANGO_SETTINGS_MODULE=aberturas.settings.dev
    env_file:
      - ./aberturas/.env
    depends_on:
      redis:
        condition: service_started
    command: >
      sh -c "python manage.py migrate &&
             python manage.py shell -c \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin@akun.com', 'admin@akun.com', 'admin123') if not User.objects.filter(email='admin@akun.com').exists() else print('Usuario ya existe')\" &&
             python manage.py runserver 0.0.0.0:8000"

  # React Frontend
  frontend:
    build: .
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=false
      - WATCHPACK_POLLING=false
      - FAST_REFRESH=true
      - GENERATE_SOURCEMAP=false
      - TSC_COMPILE_ON_ERROR=true
      - CI=true
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

  # MySQL Database - Comentado para usar DB local
  # db:
  #   image: mysql:8.0
  #   ports:
  #     - "3309:3306"
  #   environment:
  #     - MYSQL_DATABASE=akun
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=rootpass
  #     - MYSQL_ROOT_PASSWORD=rootpass
  #   volumes:
  #     - mysql_data:/var/lib/mysql

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: