version: '3.8'

services:
  # Django Backend
  backend:
    build: ./aberturas
    ports:
      - "8002:8000"
    volumes:
      - ./aberturas:/app
    environment:
      - DJANGO_SETTINGS_MODULE=aberturas.settings.dev
    env_file:
      - ./aberturas/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: >
      sh -c "python manage.py migrate &&
             python manage.py shell -c \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin@akun.com', 'admin@akun.com', 'admin123') if not User.objects.filter(email='admin@akun.com').exists() else print('Usuario ya existe')\" &&
             python manage.py runserver 0.0.0.0:8000"

  # React Frontend
  frontend:
    build: .
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      backend:
        condition: service_healthy

  # MySQL Database
  db:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      - MYSQL_DATABASE=aberturas
      - MYSQL_USER=aberturas
      - MYSQL_PASSWORD=aberturas
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: