# Generated by Django 4.2.24 on 2025-09-26 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('can_access_crm', models.BooleanField(default=False, verbose_name='Acceso a CRM')),
                ('can_access_catalog', models.BooleanField(default=False, verbose_name='Acceso a Catálogo')),
                ('can_access_orders', models.BooleanField(default=False, verbose_name='Acceso a Pedidos')),
                ('can_access_quotes', models.BooleanField(default=False, verbose_name='Acceso a Presupuestos')),
                ('can_access_reports', models.BooleanField(default=False, verbose_name='Acceso a Reportes')),
                ('can_access_settings', models.BooleanField(default=False, verbose_name='Acceso a Configuración')),
                ('can_create', models.BooleanField(default=True, verbose_name='Puede crear')),
                ('can_edit', models.BooleanField(default=True, verbose_name='Puede editar')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Puede eliminar')),
                ('can_export', models.BooleanField(default=False, verbose_name='Puede exportar')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role'),
        ),
    ]
