# Generated by Django 4.2.24 on 2025-09-26 00:00

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('is_default', models.BooleanField(default=False)),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lista de Precios',
                'verbose_name_plural': 'Listas de Precios',
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tasa de Impuesto',
                'verbose_name_plural': 'Tasas de Impuesto',
            },
        ),
        migrations.CreateModel(
            name='UoM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('length', 'Longitud'), ('area', 'Área'), ('weight', 'Peso'), ('unit', 'Unidad')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.productcategory')),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Producto',
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('material', models.CharField(choices=[('ALUMINIO', 'Aluminio'), ('PVC', 'PVC'), ('MADERA', 'Madera')], max_length=20)),
                ('opening_type', models.CharField(choices=[('CORREDIZA', 'Corrediza'), ('BATIENTE', 'Batiente'), ('OSCILOBATIENTE', 'Oscilobatiente'), ('PAÑO_FIJO', 'Paño Fijo')], max_length=20)),
                ('glass_type', models.CharField(blank=True, choices=[('SIMPLE', 'Simple'), ('DVH', 'DVH'), ('LAMINADO', 'Laminado')], max_length=20)),
                ('color_code', models.CharField(blank=True, max_length=20)),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('height_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('pricing_method', models.CharField(choices=[('FIXED', 'Precio Fijo'), ('AREA', 'Por Área')], default='FIXED', max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_per_m2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_area_m2', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('is_service', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productcategory')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.taxrate')),
                ('uom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.uom')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='PriceListRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('FIXED', 'Precio Fijo'), ('AREA', 'Por Área')], max_length=10)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_per_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Regla de Lista de Precios',
                'verbose_name_plural': 'Reglas de Lista de Precios',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='catalog_pro_sku_2c4c34_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='catalog_pro_name_f603c0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'material', 'opening_type'], name='catalog_pro_categor_26d26a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelistrule',
            unique_together={('price_list', 'product')},
        ),
    ]
