# Generated by Django 4.2.24 on 2025-09-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_plantillas'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attributeoption',
            name='catalog_attributeoption_attribute_code_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='producttemplate',
            name='catalog_producttemplate_line_name_version_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='templateattribute',
            name='catalog_templateattribute_template_code_uniq',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='catalog_pro_medida__d848fe_idx',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='medida',
        ),
        migrations.AlterUniqueTogether(
            name='attributeoption',
            unique_together={('attribute', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='producttemplate',
            unique_together={('line_name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='templateattribute',
            unique_together={('template', 'code')},
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['color', 'linea'], name='catalog_pro_color_i_06362a_idx'),
        ),
    ]
