# Generated by Django 4.2.24 on 2025-09-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_attributeoption_catalog_attributeoption_attribute_code_uniq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeoption',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='attributeoption',
            name='qty_attr_code',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='attributeoption',
            name='swatch_hex',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='templateattribute',
            name='max_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templateattribute',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='templateattribute',
            name='max_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templateattribute',
            name='min_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templateattribute',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='templateattribute',
            name='min_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templateattribute',
            name='rebaje_vidrio_mm',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='templateattribute',
            name='render_variant',
            field=models.CharField(choices=[('select', 'Select'), ('swatches', 'Swatches'), ('radio', 'Radio'), ('buttons', 'Buttons')], default='select', max_length=10),
        ),
        migrations.AddField(
            model_name='templateattribute',
            name='step_mm',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='templateattribute',
            name='step_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='templateattribute',
            name='unit_label',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='attributeoption',
            name='pricing_mode',
            field=models.CharField(choices=[('ABS', 'Suma absoluta por ítem'), ('PER_M2', 'Precio por m²'), ('PERIMETER', 'Precio por perímetro (m)'), ('FACTOR', 'Factor multiplicativo (x)'), ('PER_UNIT', 'Precio por unidad')], default='ABS', max_length=10),
        ),
        migrations.AlterField(
            model_name='templateattribute',
            name='type',
            field=models.CharField(choices=[('SELECT', 'Select'), ('BOOLEAN', 'Boolean'), ('NUMBER', 'Number'), ('DIMENSIONS_MM', 'Dimensions (mm)'), ('QUANTITY', 'Quantity')], max_length=15),
        ),
    ]
