# Generated by Django 4.2.24 on 2025-09-29 15:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código ISO de la moneda (USD, ARS, etc.)', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Nombre completo de la moneda', max_length=100)),
                ('symbol', models.CharField(help_text='Símbolo de la moneda ($, €, etc.)', max_length=5)),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Tipo de cambio respecto a la moneda base', max_digits=10)),
                ('is_default', models.BooleanField(default=False, help_text='Moneda por defecto del sistema')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['code'],
            },
        ),
    ]
