# Generated by Django 4.2.24 on 2025-09-29 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidad',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='moneda',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='moneda',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='updated_at',
        ),
    ]
