# Generated by Django 4.2.24 on 2025-09-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_cliente_credit_limit_cliente_calle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='default_price_list',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tags',
        ),
    ]
