# Generated by Django 4.2.24 on 2025-09-28 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='title',
        ),
    ]
