# Generated by Django 4.2.24 on 2025-09-29 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_subcategory'),
        ('sales', '0002_remove_quote_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
        ),
    ]
