# Generated by Django 4.2.24 on 2025-09-29 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0003_alter_quoteitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quote_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
